# Generated by Django 6.0 on 2026-01-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peofile',
            options={'default_permissions': [], 'permissions': (('add_user', '添加用户'), ('update_user', '修改用户'), ('delete_user', '删除用户'), ('show_user', '查看用户'))},
        ),
    ]
