# Generated by Django 6.0 on 2026-01-12 10:16

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_alter_peofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'permissions': (('add_group', '添加用户组'), ('update_group', '修改用户组'), ('delete_group', '删除用户组'), ('show_group', '查看用户组')),
                'default_permissions': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
