# Generated by Django 6.0 on 2026-01-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('username', models.CharField(max_length=32, verbose_name='系统用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('info', models.CharField(max_length=64, verbose_name='备注')),
            ],
            options={
                'permissions': (('add_serverUser', '添加服务器用户'), ('show_serverUser', '查看服务器用户'), ('delete_serverUser', '删除服务器用户'), ('update_serverUser', '更新服务器用户')),
                'default_permissions': [],
            },
        ),
    ]
