# Generated by Django 6.0 on 2026-01-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_serveruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='用户密码'),
        ),
    ]
