# Generated by Django 6.0 on 2026-01-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_serveruser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机名')),
                ('cup_info', models.CharField(max_length=100, verbose_name='CPU信息')),
                ('cpu_count', models.IntegerField(verbose_name='CPU个数')),
                ('eme_info', models.CharField(max_length=32, verbose_name='内存信息')),
                ('os_system', models.CharField(max_length=32, verbose_name='操作系统')),
                ('os_system_num', models.IntegerField(verbose_name='操作系统位数')),
                ('uuid', models.CharField(max_length=64, verbose_name='uuid')),
                ('sn', models.CharField(max_length=64, verbose_name='设备SN')),
                ('scan_status', models.IntegerField(choices=[(0, '连接异常'), (1, '连接正常')], verbose_name='状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建主机时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新主机时间')),
            ],
        ),
        migrations.CreateModel(
            name='NetWort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网卡名称')),
                ('ip_address', models.CharField(max_length=32, verbose_name='网卡地址')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.server')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='硬盘名称')),
                ('size', models.CharField(max_length=32, verbose_name='硬盘大小')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.server')),
            ],
        ),
    ]
