# Generated by Django 6.0 on 2026-01-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_server_networt_disk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetWort',
            new_name='NetWork',
        ),
    ]
