# Generated by Django 6.0 on 2026-01-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_rename_networt_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cup_info',
            new_name='cpu_info',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='eme_info',
            new_name='mem_info',
        ),
    ]
